# Generated by Django 5.2.7 on 2025-11-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('arquivo_leitura', models.FileField(blank=True, null=True, upload_to='livros/')),
                ('em_alta', models.BooleanField(default=False)),
            ],
        ),
    ]
