# Generated by Django 5.2.7 on 2025-11-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='arquivo_leitura',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Fantasia', 'Fantasia'), ('Ação', 'Ação'), ('Ficção Adolescente', 'Ficção Adolescente'), ('Contos', 'Contos'), ('Drama', 'Drama'), ('Gastronomia', 'Gastronomia'), ('Espiritualidade', 'Espiritualidade')], default='Romance', max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
