# Generated by Django 5.2.7 on 2025-11-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_arquivo_leitura_alter_livro_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ficha_tecnica',
            field=models.TextField(blank=True, null=True, verbose_name='Ficha Técnica (Ex: ISBN, Páginas, Editora)'),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
