# Generated by Django 5.2.7 on 2025-11-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_ficha_tecnica_livro_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='conteudo',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo do Livro (Capítulo 1, etc.)'),
        ),
    ]
