# Generated by Django 5.2.7 on 2025-11-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='arquivo_leitura',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='conteudo',
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ficha_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(max_length=100),
        ),
    ]
