# Generated by Django 5.2.7 on 2025-11-14 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_remove_livro_arquivo_leitura_remove_livro_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='conteudo',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo do Livro (Capítulo 1, etc.)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='estrelas',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='A avaliação deve ter no mínimo 1 estrela.'), django.core.validators.MaxValueValidator(5, message='A avaliação deve ter no máximo 5 estrelas.')]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Fantasia', 'Fantasia'), ('Ação', 'Ação'), ('Ficção Adolescente', 'Ficção Adolescente'), ('Contos', 'Contos'), ('Drama', 'Drama'), ('Gastronomia', 'Gastronomia'), ('Espiritualidade', 'Espiritualidade')], max_length=100),
        ),
    ]
