# Generated by Django 5.2.7 on 2025-11-19 01:10

import django.db.models.deletion
import livros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_livro_conteudo_alter_avaliacao_estrelas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('posicao_paragrafo', models.PositiveIntegerField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_leitura', to='livros.livro')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=120, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=livros.models.foto_usuario_path)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('livros_lidos', models.PositiveIntegerField(default=0)),
                ('livros_publicados', models.PositiveIntegerField(default=0)),
                ('avaliacoes_feitas', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
