# Generated by Django 5.2.7 on 2025-11-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguidores',
            options={'verbose_name_plural': 'Seguidores'},
        ),
    ]
